// thingProperties.h
// Auto-generated by Arduino IoT Cloud — credentials sourced from arduino_secrets.h

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

// Device UUID assigned in Arduino IoT Cloud dashboard
const char DEVICE_LOGIN_NAME[] = "your-device-uuid-here";

// Credentials pulled from arduino_secrets.h
const char SSID[]       = SECRET_SSID;
const char PASS[]       = SECRET_OPTIONAL_PASS;
const char DEVICE_KEY[] = SECRET_DEVICE_KEY;

// Function declarations
void onHumidityChange();
void onSoilMoistureChange();
void onTemperatureChange();
void onMotionDetectedChange();

// Cloud variables
float humidity;
float soilMoisture;
float temperature;
bool  motionDetected;

void initProperties() {
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);

  ArduinoCloud.addProperty(humidity,      READWRITE, ON_CHANGE, onHumidityChange);
  ArduinoCloud.addProperty(soilMoisture,  READWRITE, ON_CHANGE, onSoilMoistureChange);
  ArduinoCloud.addProperty(temperature,   READWRITE, ON_CHANGE, onTemperatureChange);
  ArduinoCloud.addProperty(motionDetected,READWRITE, ON_CHANGE, onMotionDetectedChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

// -------------------------
// Cloud callback functions
// -------------------------
void onHumidityChange()      {}
void onSoilMoistureChange()  {}
void onTemperatureChange()   {}
void onMotionDetectedChange(){}
